remote_theme: "jeffreytse/jekyll-theme-yat"

# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  articles:
    permalink: "/:collection/:path/"
    defaults:
      layout: post
    output: true

title: Tuan's blog
email: tuan.nguyen930708@gmail.com
author: Tuan Nguyen
description: Tell you a story of the nerd, how did I work and what can I can do
url: "https://blog.scrapnode.com" # the base hostname & protocol for your site, e.g. http://example.com

copyright: "Tuan Nguy 2022-{currentYear} {author}"

sitemap: true
paginate: 20
