title: Tuan Nguyen's blog
description: Tell you a story of the nerd, how did I work and what can I can do

remote_theme: just-the-docs/just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: light

# ga_tracking: UA-5555555-55
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

aux_links:
  "Tuan Nguyen":
    - "//kubeplusplus.github.io/cv/"
aux_links_new_tab: true

nav_sort: case_insensitive

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 Tuan Nguyen."
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p %z" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: false # show or hide edit this page link

plugins:
  - jekyll-seo-tag

# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  articles:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    articles:
      # Give the collection a name
      name: Articles
